[package]
name = "pi_3d_loader"
version = "0.0.1"
authors = [""]
edition = "2021"
description = "gltf loader"
repository = "https://github.com/GaiaWorld/pi_gltfloader"
license = "MIT OR Apache-2.0"
keywords = ["gltf loader"]

[dependencies]
approx = "0.5"
pi_gltf = {path = "../pi_gltf"}
pi_hal = { path = "E:/pi_hal"  }
serde_cbor = "0.11.2"